# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        IntegralTransforms.jl
#repo_url:         https://github.com/miguelraz/IntegralTransforms.jl
#site_description: Ain't no func like Special Function func :spock-hand:
#site_author:      mrg

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - codehilite
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Tutorial:
    - Title 1: tutorials/basicmacros.md
    - Title 2: tutorials/advancedmacros.md
    - Title 3: tutorials/macrotransforms.md
